nguage: ruby
script:
  - "puppet-lint --with-filename manifest/virtualbox.pp"
  - "rake spec"
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
branches:
  only:
   - master
env:
  - PUPPET_GEM_VERSION="~> 2.6"
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION="~> 3.0"
  - PUPPET_GEM_VERSION="~> 3.1"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.6"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.6"
